import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "../components/header";
import { Separator } from "@radix-ui/react-separator";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News-Api",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Separator />
        {children}
      </body>
    </html>
  );
}
